const shippingData = [
  { area: "Saddar", charge: 60 },
  { area: "M.A. Jinnah Road", charge: 55 },
  { area: "Empress Market", charge: 60 },
  { area: "Preedy Street", charge: 55 },
  { area: "Clifton Block 1", charge: 220 },
  { area: "Clifton Block 2", charge: 220 },
  { area: "Clifton Block 3", charge: 220 },
  { area: "Clifton Block 4", charge: 220 },
  { area: "Clifton Block 5", charge: 220 },
  { area: "Clifton Block 7", charge: 220 },
  { area: "Clifton Block 8", charge: 220 },
  { area: "Clifton Block 9", charge: 220 },
  { area: "Defence Phase 1", charge: 230 },
  { area: "Defence Phase 2", charge: 230 },
  { area: "Defence Phase 4", charge: 230 },
  { area: "Defence Phase 5", charge: 230 },
  { area: "Defence Phase 6", charge: 230 },
  { area: "Defence Phase 7", charge: 230 },
  { area: "Defence Phase 8", charge: 230 },
  { area: "Gulshan-e-Iqbal Blocks", charge: 220 },
  { area: "Gulistan-e-Jauhar Blocks", charge: 210 },
  { area: "Nazimabad Block 1–4", charge: 140 },
  { area: "North Nazimabad Blocks A–N", charge: 140 },
  { area: "Federal B Area Blocks 1–20", charge: 120 },
  { area: "North Karachi Sectors 5–11", charge: 160 },
  { area: "Malir", charge: 300 },
  { area: "Malir Cantt", charge: 290 },
  { area: "Model Colony", charge: 180 },
  { area: "Shah Faisal Colony", charge: 290 },
  { area: "Korangi", charge: 260 },
  { area: "Korangi Industrial Area", charge: 290 },
  { area: "Landhi", charge: 260 },
  { area: "Bin Qasim", charge: 360 },
  { area: "Orangi Town", charge: 200 },
  { area: "Baldia Town", charge: 160 },
  { area: "SITE Area", charge: 160 },
  { area: "Liaquatabad", charge: 90 },
  { area: "Buffer Zone", charge: 120 },
  { area: "Gulzar-e-Hijri", charge: 260 },
  { area: "PIB Colony", charge: 210 },
  { area: "Ancholi", charge: 160 },
  { area: "Gulberg", charge: 120 },
  { area: "Karachi University", charge: 210 },
  { area: "Jamshed Town", charge: 120 },
  { area: "Garden", charge: 80 },
  { area: "Soldier Bazaar", charge: 60 },
  { area: "Kharadar", charge: 65 },
  { area: "Lyari", charge: 110 },
  { area: "Keamari", charge: 290 },
  { area: "Maripur", charge: 400 },
  { area: "Hawksbay", charge: 480 },
  { area: "Manghopir", charge: 230 },
  { area: "Surjani Town", charge: 250 },
  { area: "New Karachi", charge: 250 },
  { area: "Shahrah-e-Faisal", charge: 90 },
  { area: "Tariq Road", charge: 160 },
  { area: "Bahadurabad", charge: 90 },
  { area: "PECHS", charge: 140 },
  { area: "Cantt Station", charge: 120 },
  { area: "City Station", charge: 50 },
  { area: "Drigh Road", charge: 120 }
];

module.exports = shippingData;
